---
title: "Additional resources"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 2
---

\

### Resources will be added here before and during workshop!

\

# Papers

- Exploring the fit of phylogenetic models to morphological data (model adequacy), see [Mulvey et al. (2024)](https://academic.oup.com/sysbio/advance-article-abstract/doi/10.1093/sysbio/syae055/7814882)
- Estimating trees or rates, when origination, extinction and sampling vary through time (birth-death skyline models), see [Allen et al. (2024)](https://www.cambridge.org/core/journals/cambridge-prisms-extinction/article/mechanistic-phylodynamic-models-do-not-provide-conclusive-evidence-that-nonavian-dinosaurs-were-in-decline-before-their-final-extinction/A4B969E201DF64596175127357991F4B) or [Allen et al. (2025)](https://www.lyellcollection.org/doi/full/10.1144/SP549-2023-174)
- Dating super trees using the fossilised birth-death process, see [Godoy et al. (2019)](https://bmcecolevol.biomedcentral.com/articles/10.1186/s12862-019-1466-4), see also [Bapst (2016)](https://www.cambridge.org/core/journals/paleobiology/article/abs/assessing-the-effect-of-timescaling-methods-on-phylogenybased-analyses-in-the-fossil-record/082F239A2512CC09E51181F9B499D1A3)
- *Practical guidelines for Bayesian phylogenetic inference using Markov chain Monte Carlo (MCMC)* [Barido-Sottani et al. (2024)](https://open-research-europe.ec.europa.eu/articles/3-204)

# Software tutorials

An extended version of the FBD tutorial for total-evidence anylsis can be found on the [Taming the Beast site](https://taming-the-beast.org/tutorials/FBD-tutorial/) and the [RevBayes tutorial page](https://revbayes.github.io/tutorials/).

# Simulations

You can also use simulations to explore assumptions of the FBD process (and related birth-process models) using the [FossilSim](https://github.com/fossilsim/fossilsim) R package application [FossilSimShiny](https://github.com/fossilsim/FossilSimShiny). Associated exercise available [here](https://phylogenetics-fau.netlify.app/fossilsimshiny).


