---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

### Workshop material will be posted here before Tuesday!

\

# Overview

1. Intro to Bayesian tree inference (09:00 - 10:00)
2. Model adequacy (10:00 - 11:00)
3. Intro to Bayesian time-tree inference (11:00 - 12:00)
4. Panel discussion (12:00 - 12:30)

# Bayesian tree inference

```{r, echo = FALSE}
library(kableExtra)

#urls <- c("slides/01-intro.pdf","exercise-01.html")
urls <- c("slides/01-intro.pdf", "tree-inference.html")

dt <- data.frame(links = c("Slides", 
                              "Exercise 1"),
                 topics = c("Intro to Bayesian tree inference", 
                            "Tree inference using RevBayes"
                            ))

dt$links[1] <- paste0("[", dt$links[1], "](", urls[1], ")")
dt$links[2] <- paste0("[", dt$links[2], "](", urls[2], ")")

kbl(dt) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

```

# Model Adequacy

```{r, echo = FALSE}
library(kableExtra)

#urls <- c("slides/01-intro.pdf","exercise-01.html")
urls <- c("", "ModelAdequacy.html")

dt <- data.frame(links = c("Slides", 
                              "Exercise 2"),
                 topics = c("Model adequacy",
                            "Model adequacy in RevBayes"))

dt$links[1] <- paste0("[", dt$links[1], "](", urls[1], ")")
dt$links[2] <- paste0("[", dt$links[2], "](", urls[2], ")")

kbl(dt) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

```

*Short break!!*

# Birth-death sampling models

```{r, echo = FALSE}
library(kableExtra)

#urls <- c("slides/01-intro.pdf","exercise-01.html")
urls <- c("", "")

dt <- data.frame(links = c("Slides", 
                              "Exercise 3"),
                 topics = c("Birth-death sampling process models",
                            "tbd"))

dt$links[1] <- paste0("[", dt$links[1], "](", urls[1], ")")
dt$links[2] <- paste0("[", dt$links[2], "](", urls[2], ")")

kbl(dt) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

```
